ECHO Preparing to boot and run PDP-11 Single User BASIC on SIM-H Emulator

; Set CPU parameters - PDP-11/05 with 8kW (16kB) of core memory
SET CPU 11/05
SET CPU 64K

; Disable devices not used by BASIC
SET HK DISABLE
SET RHA DISABLE
SET DZ DISABLE
SET RL DISABLE
SET RX DISABLE
SET RP DISABLE
SET RQ DISABLE
SET TM DISABLE
SET TQ DISABLE
SET RK DISABLE

; Enable the high-speed paper tape reader and punch
SET PTR ENABLE
SET PTP ENABLE

; Deposit the Bootstrap Loader into core memory
; This version assumes :
; 8kW (16kB) of core memory available
; high-speed paper tape reader/punch
DEPOSIT 037744 016701
DEPOSIT 037746 000026
DEPOSIT 037750 012702
DEPOSIT 037752 000352
DEPOSIT 037754 005211
DEPOSIT 037756 105711
DEPOSIT 037760 100376
DEPOSIT 037762 116162
DEPOSIT 037764 000002
DEPOSIT 037766 037400
DEPOSIT 037770 005267
DEPOSIT 037772 177756
DEPOSIT 037774 000765
DEPOSIT 037776 177550

; Attach the Absolute Loader paper tape
ATTACH PTR DEC-11-L2PC-PO.ptap

go 037744

; set console telnet=5000
; Attach the Single User BASIC paper tape
attach ptr DEC-11-AJPB-PB.ptap
dep sr 0
go
